### ISSUE TITLE
Error in setnames when running create.sumtable

### ISSUE THREAD

**Issue by tammyyyx** [ImmuneDynamics/Spectre#10]
Hi Thomas,

After fixing the C stack issue (thanks for the solution), I encountered another error message that says "Creating summary table
 -- processing sample 50002
Error in setnames(x, value) : 
  Can't assign 1 names to a 0 column data.table"

I checked my cell.data data table it looks like the one shown in simple workflow. This occurs with and without the count argument or the annotation argument. Do you know what might be causing this problem?

Thanks so much!

Tammy

**Comment by tomashhurst** [comment]
Hmm interesting. It looks like it's not filtering the original data.table the way you want. Could you copy in the code you ran, and the names of the columns in your data.table?

**Comment by tammyyyx** [comment]
Hi Thomas, 

I figured out the problem. I was trying to skip the annotation part, and use pop.col="Cluster" in create.sumtable. Now I added some made up population names and went through the whole thing including the annotation part and reran create.sumtable with pop.col="Population" and it worked. Not sure if the error occurs bc I made some mistake skipping the annotation step or bc  create.sumtable function requires annotation to run prior to it. Thanks!

**Comment by tomashhurst** [comment]
@tammyyyx well spotted! You can use either the cluster or population (i.e. annotated cluster) labels to create the summary data, it just requires the user to specify which. In the worked example we set it up to use the 'population' labels. We might add a note to clarify at that step.

Good luck!
