### ISSUE TITLE
write.files(cell.dat, i, write.csv = FALSE, write.fcs = TRUE)

### ISSUE THREAD

**Issue by sailseem** [ImmuneDynamics/Spectre#105]
Well, when i follow the tutorial and write files to facs, I got the error like this.

  write.files(cell.dat, i, write.csv = FALSE, write.fcs = TRUE)
Error in getClass(Class, where = topenv(parent.frame())) : 
  “flowFrame” is not a defined class

can you help me with it? Thanks

**Comment by tomashhurst** [comment]
@sailseem that's an interesting error -- what happens if you just run `cell.dat` at that point?

**Comment by tomashhurst** [comment]
@sailseem did you manage to get this working? It's possible that the flowFrame package wasn't installed correctly.
