### ISSUE TITLE
where to follow the cellular and spatial analysis

### ISSUE THREAD

**Issue by sailseem** [ImmuneDynamics/Spectre#106]
Dear,
    may i know where to continue the cellular and spatial analysis like this? How to generate the UMAP plot after spatial info to data.info?

![image](https://user-images.githubusercontent.com/72428172/132227815-d995a58d-3d13-49e3-8445-6c212482a739.png)

Thanks

**Comment by tomashhurst** [comment]
@sailseem the three scripts will be in the folder indicated at the start of the instruction page, with comments to guide you along. We just haven't finished writing the online guide yet. Give it a shot with the scripts and see if it all makes sense.
