### ISSUE TITLE
Unsuccessful installation of Spectre

### ISSUE THREAD

**Issue by raquel-galfig** [ImmuneDynamics/Spectre#113]
When I was trying to install Spectre, I got the following error:

ERROR: dependency ‘rgeos’ is not available for package ‘Spectre’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Spectre’
Warning messages:
  1: In i.p(...) : installation of package ‘rgeos’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/00/r8m4x_k962980kd3qlyj2wq00312hl/T//Rtmpc0qacc/file12e0b2d599ed2/Spectre_1.0.0.tar.gz’ had non-zero exit status

Then, I tried the following code:

if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
if(!require('rgeos')) {BiocManager::install('rgeos')}

And because I was not able to install 'rgeos', I got the following error:

Warning messages:
  1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
                  there is no package called ‘rgeos’
                2: In install.packages(...) :
                  installation of package ‘rgeos’ had non-zero exit status

How can I solve this issue?

Thanks in advance.
Best,
Raquel

**Comment by SamGG** [comment]
I would check the messages before the warning. There might a package on which rgoes is depending that is missing. When installation is going weird, we have to patiently solve every dependency.

**Comment by tomashhurst** [comment]
Hi @raquel-galfig , thanks for reaching out! What operating system are you using? 

`rgeos` should be available from CRAN, so try running `install.packages('rgeos')` and see if that works?

**Comment by tomashhurst** [comment]
@raquel-galfig I'm going to close this one for now -- let us know if `install.packages('rgeos')` doesn't solve the issue.
