### ISSUE TITLE
truncate_max_range = FALSE

### ISSUE THREAD

**Issue by dietmar113** [ImmuneDynamics/Spectre#121]
Hi,
I got this Warning:
1: In readFCSdata(con, offsets, txt, transformation, which.lines, scale,  :
  Some data values of 'eFluor 450-A' channel exceed its $PnR value 4194304 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'

and wanted to avoid the truncation by adding "truncate_max_range = FALSE" to the function:
Spectre::read.files(file.loc = InputDirectory, 
		file.type = ".fcs", truncate_max_range = FALSE
		do.embed.file.names = TRUE)

which does not work.

How will it work?

Thank you,

**Comment by SamGG** [comment]
Hi,
The function in the read.Files.R file has no extra options (...) passed to the read.FCS function.
This will not work unless you modify the code yourself, which is easy if you know a little bit of R.
Best.

**Comment by ghar1821** [comment]
I've added the extra options to `read.files`. You can now use `truncate_max_range` parameter which will simply be passed on to flowCore's read.FCS function. 

For now, to use it, please install the package version in the development branch using `devtools::install_github("immunedynamics/spectre", ref='development')`
