### ISSUE TITLE
‘simple’ discovery analysis workflow

### ISSUE THREAD

**Issue by sailseem** [ImmuneDynamics/Spectre#125]
Dear developer,
 
I am just wondering that can I analyze the IMC data using simple discovery analysis workflow? If so, how can I deal with the x and y position information as data input?

Thanks a lot,
fan

**Comment by ghar1821** [comment]
Yes you can, but you will need to first do image segmentation. We have a protocol that you can try: https://wiki.centenary.org.au/display/SPECTRE/Protocol%3A+multi-cut+cell+segmentation+using+Ilastik

After that you can load the data into R and run the discovery workflow. We have some sample scripts to do this in the repository: https://github.com/ImmuneDynamics/Spectre/tree/master/workflows/Spatial%20-%20advanced/Spectre%20advanced%20spatial.

We've started writing out a guided tutorial, but haven't finished them yet (https://immunedynamics.io/spectre/spatial-advanced). Finding time to do it is not easy these days.

**Comment by sailseem** [comment]
Thank you very much, that's so cool and we are looking forward to the complete tutorials. What a nice package!!! Thanks

**Comment by sailseem** [comment]
sorry, one more question. What are the major differences between these two segmentation methods, or they are actually the same? Which one do you recommend?
[Protocol: multi-cut cell segmentation using Ilastik](https://wiki.centenary.org.au/display/SPECTRE/Protocol%3A+multi-cut+cell+segmentation+using+Ilastik)

[Protocols: modified Bodenmiller segmentation pipeline (IMCtools, CellProfiler, Ilastik, HistoCat)](https://wiki.centenary.org.au/pages/viewpage.action?pageId=199630736)
[Skip to end of metadata](https://wiki.centenary.org.au/pages/viewpage.action?pageId=199630736#page-metadata-end)

**Comment by sailseem** [comment]
By using the protocol here [Protocols: modified Bodenmiller segmentation pipeline (IMCtools, CellProfiler, Ilastik, HistoCat)](https://wiki.centenary.org.au/pages/viewpage.action?pageId=199630736)

I got an error when I execute the sample data, 
![image](https://user-images.githubusercontent.com/72428172/158023698-3cf01be5-722f-4a16-8dea-1a17ba0fd07f.png)
And we don't have the access to the troubleshooting page
![image](https://user-images.githubusercontent.com/72428172/158023732-438e5c63-7c41-4da6-9738-007ce538dfbe.png)
![image](https://user-images.githubusercontent.com/72428172/158023801-dbc1830e-cd8f-4d9e-a206-d408936920b2.png)

And the data folder only has the MCD file in zip file, no txt file at all, is this the problem?
Thanks a lot and sorry for so many questions for this.

**Comment by ghar1821** [comment]
Sorry for not getting back sooner. @tomashhurst can you fix the permission to the troubleshooting page?

I recommend trying the ilastik protocol - it's our preferred one these days.

**Comment by tomashhurst** [comment]
@sailseem the 'multicut' option is our go-to option these days, and in general it should be easier to user. Have you had a go at that one?

**Comment by tomashhurst** [comment]
For that troubleshooting page, I have updated the link on the protocol page, and you can access it here: https://wiki.centenary.org.au/x/hSDmCw.
