### ISSUE TITLE
Unable to install Spectre for RStudio Version 3.6.3

### ISSUE THREAD

**Issue by jamila-griffith** [ImmuneDynamics/Spectre#135]
Hi,

I am trying to install Spectre for RStudio (3.6.3) but get an error that Spectre is not available for RStudio version 3.6.3. Can you please help. 
devtools::install_github("immunedynamics/spectre")

Thanks

**Comment by tomashhurst** [comment]
Hi @jamila-griffith ,

Thanks for reaching out! Do you get any other errors? Sometimes that message comes up because something else has gone wrong during the installtion.

Tom
