### ISSUE TITLE
Issue when running FlowSOM in Simple Discovery Workflow

### ISSUE THREAD

**Issue by SamN01** [ImmuneDynamics/Spectre#138]
Hi, 

I'd like to firstly say thank you for providing such well thought out package to analysis flow data in R. I cannot wait to take full advantage of it. 

I have just started using Spectre with a simple flow exp. following the Simple Discovery Workflow to get me started and I got up to the Clustering and Dimensionality reduction ssection without an issue. 

When I try and run the flowsom command I receive this error: 

    > cell.dat <- run.flowsom(cell.dat, cluster.cols, meta.k = 8)
    Preparing data
    Starting FlowSOM
    Building SOM
    
    Error in SOM(fsom$data[, colsToUse], silent = silent, ...) : 
      NA/NaN/Inf in foreign function call (arg 1)

I proceed to continue thinking it may not matter but I cannot generate a plot further down so I think I need to resolve this issue first. 

Any help would be greatly appreciated. 

Thanks.

**Comment by SamN01** [comment]
I solved this. When merging my data tables, I had no values in a column resulting in the NA error. I removed my rows that had no data in them and this solved my issue.

**Comment by tomashhurst** [comment]
@SamN01 nice one! The other option is just to exclude the columns that have `NA` in them from the `clustering.cols`.
