### ISSUE TITLE
Install problem for R version 4.2.1

### ISSUE THREAD

**Issue by charlottedevries** [ImmuneDynamics/Spectre#142]
Hi, 

I have tried to install Spectre package, but I face some problems. First I thought it was the problem that I had not updated my R version, but now that I am running 4.2.1 it still does not work. 
following this 
```
if(!require('devtools')) {install.packages('devtools')}
devtools::install_github("immunedynamics/spectre")

```
gives me a very long error ending with: 
`“installation of package ‘/var/folders/89/qs39dbjs0s96m8zm69nymx7116z4d5/T//Rtmpcprnft/filec5b41fced90f/Spectre_1.0.0.tar.gz’ had non-zero exit status” `

and
`Spectre::package.check() `
gives: 
`Error in loadNamespace(x) : there is no package called ‘Spectre’`

I hope someone has a suggestion! 

Thanks, 
Charlotte

**Comment by ghar1821** [comment]
Hi @charlottedevries

Sorry for the late response. It has been a hectic year for us. 
Is it possible to paste the error message before that last line? Fully understand if it is not possible as it has been a while.

**Comment by tomashhurst** [comment]
Hi @charlottedevries , there will likely have been an error message a few lines before this one you mentioned:

```“installation of package ‘/var/folders/89/qs39dbjs0s96m8zm69nymx7116z4d5/T//Rtmpcprnft/filec5b41fced90f/Spectre_1.0.0.tar.gz’ had non-zero exit status” ```

Could you see which it was?

**Comment by tomashhurst** [comment]
Glad to hear it!
