### ISSUE TITLE
How to identify and remove "bad/outlier" FCS files objectively, before performing clustering?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ImmuneDynamics/Spectre#148]
Hi there, 

Thanks for the workflow.

flowAI can help remove technical error by removing actual events, but not the whole FCS file (http://127.0.0.1:18637/library/flowAI/doc/flowAI.html). 

In my data, by manually examining the staining profile, I identified some FCS files that had "outlier" staining pattern (across markers) and aim to remove these FCS files from the clustering analysis, but is there a way to objectively remove certain whole FCS files instead of just visually deciding?

Or, is it a best practice to only remove outlier events and not the whole file?

Thank you again for your help.

**Comment by ghar1821** [comment]
Not sure I understand what you mean by removing outlier events vs removing the entire files. Do you have several outliers in one FCS file? or the entire FCS file has weird staining pattern? 

If the latter, I suppose it make sense to just not include that FCS file in your analysis.

If you want to remove just the outlier cells in a given FCS files, you can load it up as `data.table` first, then just keep cells which expression is less than or greater than some values in certain channel? Just a simple filter on the `data.table` like:

```
cell.dat <- cell.dat[Yb176_MHCII <= 10, ]
```

**Comment by denvercal1234GitHub** [comment]
Thank you @ghar1821! A reviewer commented that if we simply remove the FCS files after manually examining the staining profile in FlowJo instead of some unbiased statistical modeling then we were almost Cherry-picking. What is your opinion? Thanks again!

**Comment by tomashhurst** [comment]
Hi @denvercal1234GitHub ,

> A reviewer commented that if we simply remove the FCS files after manually examining the staining profile in FlowJo instead of some unbiased statistical modeling to first identify the troublesome FCS file, then we were almost Cherry-picking. What is your opinion?

I think the issue here is around objectivity -- why exclude some files but not others, etc. Excluding some files because of cell quality issues (e.g. too many dead cells etc) or data quality issues (signal shifting across acquisition time) can be reasonable, but you would need some kind of objective rational for why each is excluded, such that a reviewer can assess. However, if it is not a data quality issue, then those differences may well be representing genuine biological differences, and are worth including.

Can you provide any more info?

**Comment by denvercal1234GitHub** [comment]
Thanks @tomashhurst. So we have about 200 wells. Each well was stained with the same backbone antibodies, but for a PE channel, each well has a different antibody. The files that have different staining patterns for non-PE markers turned out to be the wells with the highest staining intensity for PE compared to the other wells. Note that in our case, the PE-Abs for these wells did not get titrated because it was preconjugated to the plate for us (we cannot change the amount). 

I hope to at least perform some sort of PCA plot to see whether these FCS would cluster together away from the rest of the hundreds of files? Do you have a script handy for this PCA checking?

Thank you so much!
