### ISSUE TITLE
Real or technical artifacts due to errors detected in UMAP following run.flowsom()?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ImmuneDynamics/Spectre#161]
Hi there, 

Thanks for the package. 

When I used `run.flowsom` even with `meta.k=20` (automatic `meta.k` resolved 11 clusters), the cluster UMAP doesn't look "right" -- they clumped together on 1 side of the UMAP, and there two tiny clusters that are so separated from everyone. 

Do you think these 2 clusters (6 and 20) are simply artifacts? If so, would you mind suggesting some ways to assess that? 

Thank you for your help!

![Screenshot 2023-04-27 at 12 07 09](https://user-images.githubusercontent.com/62179082/234844537-1250bde9-adbb-4267-8ba0-a895d40c7afb.png)

Related to #154.

**Comment by denvercal1234GitHub** [comment]
thanks @tomashhurst ! This is very useful. Would you mind elaborating a bit more on which plotting would you be doing to investigate whether these are cells of technical artifact? These 2 populations are actually what we expect to detect in our data based on RNAseq of the same samples.

**Comment by tomashhurst** [comment]
@denvercal1234GitHub sorry for the delayed reply here -- essentially an nxn plot -- so CD3 vs CD4, CD3 vs CD19, CD3 vs N etc. In each, plotting the metacluster. You could also create a heatmap to look at what markers are expressed most highly using `make.pheatmap`.

There will _likely_ be some group of cells that may have ultra-high expression on a set of markers, possibly as these might be some kind of aggregate. You could also plot them on tSNE of FItSNE which should squish them into the 2D plot a bit better which might allow you to see how they look compared to the remaining cells in the dataset.

I'll close this for now, but let us know how you get on.
