### ISSUE TITLE
Error with prep.cytonorm

### ISSUE THREAD

**Issue by MattCrossley99** [ImmuneDynamics/Spectre#169]
Hi,

I'm having an issue trying to run prep.cytonorm, the output is as follows:

```
Step 1/3. Mapping data
Step 2/3. Merging data
Step 3/3. Returning data
Step 1/4 - Splitting files for use with original FlowSOM function
Step 2/4 - Running FlowSOM
Reading 15.fcs
Error in if (sampleWithReplacement & (nrow(f) < cFile)) { : 
  argument is of length zero
```

I've found a couple of issues with this same problem but they seem to be out of date, the solution for those issues was to update the FlowSOM package, however I've updated all the packages used and this hasn't fixed the issue. These issues also used FlowSOM 1.12.0 when the current version is 2.8.0. 

Any help with this would be greatly appreciated!

**Comment by ghar1821** [comment]
Hi there, can you try re-installing Spectre from the development branch and see if the error goes away?

**Comment by MattCrossley99** [comment]
That looks to have worked! Strangely the first time I got the same error but I may have somehow been using the master branch, after a bunch of reinstalling (and trying 'v2' which doesn't get very far) it worked the second time.

Also NB: dev branch requires 'limma' which isn't called as a dependancy.

**Comment by tomashhurst** [comment]
The issue is due to an update with FlowSOM that we had to create some adjustments for in the dev version. Glad to hear it worked out! Well spotted regarding limma, we will add that to the dependancy list!
