### ISSUE TITLE
The data Error: object 'merge.channels' not found in Ilastik Protocol.

### ISSUE THREAD

**Issue by andreyevteev23** [ImmuneDynamics/Spectre#175]
Hi All, 

We've been trying to go through the Ilastik protocol:

https://wiki.centenary.org.au/display/SPECTRE/Protocol%3A+multi-cut+cell+segmentation+using+Ilastik?fbclid=IwAR2zLO9_V2-K3m5Y73S8luvQf3J1H3i6eVzCEz-BLV94UxPLUoSaCnlqEtU#Protocol:multicutcellsegmentationusingIlastik-CreateHDF5fileforIlastik

And when reaching the HDF5 file save with this argument: merge.channels = merge.channels we get this: 

'data Error: object 'merge.channels' not found'.

What can be the reason for this and how can we fix this? 

Thanks!

**Comment by tomashhurst** [comment]
Hi @andreyevteev23 , if you have a look at this script, you can see how it is used (https://github.com/ImmuneDynamics/Spectre/blob/master/workflows/Spatial%20-%20advanced/data/Segmentation%20-%20process%20TIFFs.R)

```merge.channels <- for.ilastik[c(1:6)]```

In this case, we are selecting channels that are going to be blended together to form a kind of pan-cellular channel, which is useful in the Ilastik steps (it will be channel 0). You don't need to use it, you can just delete the ```merge.channels = merge.channel``` argument and go ahead without it.

**Comment by tomashhurst** [comment]
@andreyevteev23 I'm going to close this for now, let us know if you run into any issues.
