### ISSUE TITLE
cannot install on an ARM mac

### ISSUE THREAD

**Issue by chintanparekh2301** [ImmuneDynamics/Spectre#181]
Hi
Tried installing spectre on an M1 mac. The installation fails. Looks like theres an issue with the package "ALL"
Here's the output
Thanks
Installing 49 packages: terra, RcppParallel, wk, units, s2, classInt, estimability, scatterplot3d, multcompView, leaps, flashClust, emmeans, ellipse, SQUAREM, lava, diagram, timechange, prodlim, tzdb, timeDate, lubridate, ipred, hardhat, gower, clock, rhdf5filters, ALL, sf, raster, stringfish, RApiSerialize, graphlayouts, tidygraph, FactoMineR, dendextend, recipes, pROC, ModelMetrics, rhdf5, exactextractr, qs, stars, tiff, ggraph, factoextra, ggpointdensity, caret, ggthemes, HDF5Array
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/terra_1.7-65.tgz'
Content type 'application/x-gzip' length 97474072 bytes (93.0 MB)
==================================================
downloaded 93.0 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/RcppParallel_5.1.7.tgz'
Content type 'application/x-gzip' length 584884 bytes (571 KB)
==================================================
downloaded 571 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/wk_0.9.1.tgz'
Content type 'application/x-gzip' length 1967165 bytes (1.9 MB)
==================================================
downloaded 1.9 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/units_0.8-5.tgz'
Content type 'application/x-gzip' length 957884 bytes (935 KB)
==================================================
downloaded 935 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/s2_1.1.5.tgz'
Content type 'application/x-gzip' length 11907816 bytes (11.4 MB)
==================================================
downloaded 11.4 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/classInt_0.4-10.tgz'
Content type 'application/x-gzip' length 500344 bytes (488 KB)
==================================================
downloaded 488 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/estimability_1.4.1.tgz'
Content type 'application/x-gzip' length 40662 bytes (39 KB)
==================================================
downloaded 39 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/scatterplot3d_0.3-44.tgz'
Content type 'application/x-gzip' length 348793 bytes (340 KB)
==================================================
downloaded 340 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/multcompView_0.1-9.tgz'
Content type 'application/x-gzip' length 115755 bytes (113 KB)
==================================================
downloaded 113 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/leaps_3.1.tgz'
Content type 'application/x-gzip' length 102472 bytes (100 KB)
==================================================
downloaded 100 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/flashClust_1.01-2.tgz'
Content type 'application/x-gzip' length 25365 bytes (24 KB)
==================================================
downloaded 24 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/emmeans_1.9.0.tgz'
Content type 'application/x-gzip' length 2157888 bytes (2.1 MB)
==================================================
downloaded 2.1 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/ellipse_0.5.0.tgz'
Content type 'application/x-gzip' length 218284 bytes (213 KB)
==================================================
downloaded 213 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/SQUAREM_2021.1.tgz'
Content type 'application/x-gzip' length 178436 bytes (174 KB)
==================================================
downloaded 174 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/lava_1.7.3.tgz'
Content type 'application/x-gzip' length 2570013 bytes (2.5 MB)
==================================================
downloaded 2.5 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/diagram_1.6.5.tgz'
Content type 'application/x-gzip' length 677608 bytes (661 KB)
==================================================
downloaded 661 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/timechange_0.2.0.tgz'
Content type 'application/x-gzip' length 884298 bytes (863 KB)
==================================================
downloaded 863 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/prodlim_2023.08.28.tgz'
Content type 'application/x-gzip' length 436616 bytes (426 KB)
==================================================
downloaded 426 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/tzdb_0.4.0.tgz'
Content type 'application/x-gzip' length 1240219 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/timeDate_4032.109.tgz'
Content type 'application/x-gzip' length 1427112 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/lubridate_1.9.3.tgz'
Content type 'application/x-gzip' length 987159 bytes (964 KB)
==================================================
downloaded 964 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/ipred_0.9-14.tgz'
Content type 'application/x-gzip' length 389018 bytes (379 KB)
==================================================
downloaded 379 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/hardhat_1.3.0.tgz'
Content type 'application/x-gzip' length 832025 bytes (812 KB)
==================================================
downloaded 812 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/gower_1.0.1.tgz'
Content type 'application/x-gzip' length 216565 bytes (211 KB)
==================================================
downloaded 211 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/clock_0.7.0.tgz'
Content type 'application/x-gzip' length 5068374 bytes (4.8 MB)
==================================================
downloaded 4.8 MB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/rhdf5filters_1.10.1.tgz'
Content type 'application/x-compressed-tar' length 753584 bytes (735 KB)
==================================================
downloaded 735 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/sf_1.0-15.tgz'
Content type 'application/x-gzip' length 86900092 bytes (82.9 MB)
==================================================
downloaded 82.9 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/raster_3.6-26.tgz'
Content type 'application/x-gzip' length 4831693 bytes (4.6 MB)
==================================================
downloaded 4.6 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/stringfish_0.16.0.tgz'
Content type 'application/x-gzip' length 1220476 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/RApiSerialize_0.1.2.tgz'
Content type 'application/x-gzip' length 22831 bytes (22 KB)
==================================================
downloaded 22 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/graphlayouts_1.0.2.tgz'
Content type 'application/x-gzip' length 4500329 bytes (4.3 MB)
==================================================
downloaded 4.3 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/tidygraph_1.3.0.tgz'
Content type 'application/x-gzip' length 634289 bytes (619 KB)
==================================================
downloaded 619 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/FactoMineR_2.9.tgz'
Content type 'application/x-gzip' length 3806176 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/dendextend_1.17.1.tgz'
Content type 'application/x-gzip' length 3906480 bytes (3.7 MB)
==================================================
downloaded 3.7 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/recipes_1.0.9.tgz'
Content type 'application/x-gzip' length 1599104 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/pROC_1.18.5.tgz'
Content type 'application/x-gzip' length 1127987 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/ModelMetrics_1.2.2.2.tgz'
Content type 'application/x-gzip' length 560401 bytes (547 KB)
==================================================
downloaded 547 KB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/rhdf5_2.42.1.tgz'
Content type 'application/x-compressed-tar' length 2752800 bytes (2.6 MB)
==================================================
downloaded 2.6 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/exactextractr_0.10.0.tgz'
Content type 'application/x-gzip' length 2483545 bytes (2.4 MB)
==================================================
downloaded 2.4 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/qs_0.25.7.tgz'
Content type 'application/x-gzip' length 3798491 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/stars_0.6-4.tgz'
Content type 'application/x-gzip' length 4154657 bytes (4.0 MB)
==================================================
downloaded 4.0 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/tiff_0.1-12.tgz'
Content type 'application/x-gzip' length 1948558 bytes (1.9 MB)
==================================================
downloaded 1.9 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/ggraph_2.1.0.tgz'
Content type 'application/x-gzip' length 4607099 bytes (4.4 MB)
==================================================
downloaded 4.4 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/factoextra_1.0.7.tgz'
Content type 'application/x-gzip' length 416918 bytes (407 KB)
==================================================
downloaded 407 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/ggpointdensity_0.1.0.tgz'
Content type 'application/x-gzip' length 46128 bytes (45 KB)
==================================================
downloaded 45 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/caret_6.0-94.tgz'
Content type 'application/x-gzip' length 3587237 bytes (3.4 MB)
==================================================
downloaded 3.4 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/ggthemes_5.0.0.tgz'
Content type 'application/x-gzip' length 443755 bytes (433 KB)
==================================================
downloaded 433 KB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/HDF5Array_1.26.0.tgz'
Content type 'application/x-compressed-tar' length 9985746 bytes (9.5 MB)
==================================================
downloaded 9.5 MB

The downloaded binary packages are in
	/var/folders/1d/nnj_zbrn2_l3zl_yqqhs67t00000gn/T//RtmpwigHh2/downloaded_packages
installing the source package ‘ALL’

trying URL 'https://bioconductor.org/packages/3.16/data/experiment/src/contrib/ALL_1.40.0.tar.gz'
Content type 'application/gzip' length 11383132 bytes (10.9 MB)
==================================================
downloaded 10.9 MB

Error in eval(quote({ : object '..version..' not found
Calls: source ... local -> eval.parent -> eval -> eval -> eval -> eval
Execution halted

The downloaded source packages are in
	‘/private/var/folders/1d/nnj_zbrn2_l3zl_yqqhs67t00000gn/T/RtmpwigHh2/downloaded_packages’
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/1d/nnj_zbrn2_l3zl_yqqhs67t00000gn/T/RtmpwigHh2/remotesce2d59c96fec/ImmuneDynamics-Spectre-d0dd8d4/DESCRIPTION’ ...
─  preparing ‘Spectre’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘Spectre_1.1.0.tar.gz’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘Spectre/workflows/Spatial - advanced/Spectre advanced spatial/Adv spatial 3 - quantitative analysis.R’
   
Error in eval(quote({ : object '..version..' not found
Calls: source ... local -> eval.parent -> eval -> eval -> eval -> eval
Execution halted
Warning messages:
1: In i.p(...) : installation of package ‘ALL’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/1d/nnj_zbrn2_l3zl_yqqhs67t00000gn/T//RtmpwigHh2/filece2d7ee46839/Spectre_1.1.0.tar.gz’ had non-zero exit status

**Comment by SamGG** [comment]
Hi,
Try to install ALL Bioconductor package on its own. If it succeeds, install Spectre.
```
BiocManager::install("ALL", update = FALSE)
```
The current release of Bioconductor is 3.18, you are using 3.16. @tomashhurst I don't know if it's a problem.
Best.
NB: please, click on Preview button before, all these big font characters make your message less clear to me.

**Comment by chintanparekh2301** [comment]
thanks- worked!
I updated OS to Sonoma, R to 4.3, bioconductor to 3.18, installed xcode 15, and then it worked

**Comment by tomashhurst** [comment]
Glad to hear it! Any further issues let us know. Good luck!
