### ISSUE TITLE
Discovery workflow with batch alignment using CytoNorm -- link broken 

### ISSUE THREAD

**Issue by mariecrane** [ImmuneDynamics/Spectre#189]
I'm trying to access your discovery workflow with batch alignment using CytoNorm but the [link](https://immunedynamics.io/spectre/cytometry/[https://wiki.centenary.org.au/x/zGCdCw](https://unisyd-my.sharepoint.com/:b:/g/personal/thomas_ashhurst_sydney_edu_au/ER-lPRlANL5BroO3cYIV1XMBBKETa4Ufa_4KtqjJtxyPUA?e=a0ashi)) appears to be broken. Is there documentation available elsewhere while the site is down?

**Comment by tomashhurst** [comment]
Ah apologies that’s our fault, will update it shortly — but here is the actual link:

https://unisyd-my.sharepoint.com/personal/thomas_ashhurst_sydney_edu_au/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fthomas%5Fashhurst%5Fsydney%5Fedu%5Fau%2FDocuments%2FShared%2FSpectre%20PDFs%2FDiscovery%20workflow%20with%20batch%20alignment%20using%20CytoNorm%2Dv19%2D20240415%5F044409%2Epdf&parent=%2Fpersonal%2Fthomas%5Fashhurst%5Fsydney%5Fedu%5Fau%2FDocuments%2FShared%2FSpectre%20PDFs&ga=1

Tom
________________________________
From: Marie Crane ***@***.***>
Sent: Tuesday, May 14, 2024 16:13
To: ImmuneDynamics/Spectre ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ImmuneDynamics/Spectre] Discovery workflow with batch alignment using CytoNorm -- link broken (Issue #189)


I'm trying to access your discovery workflow with batch alignment using CytoNorm but the link<https://immunedynamics.io/spectre/cytometry/%5Bhttps://wiki.centenary.org.au/x/zGCdCw%5D(https://unisyd-my.sharepoint.com/:b:/g/personal/thomas_ashhurst_sydney_edu_au/ER-lPRlANL5BroO3cYIV1XMBBKETa4Ufa_4KtqjJtxyPUA?e=a0ashi)> appears to be broken. Is there documentation available elsewhere while the site is down?

**Comment by mariecrane** [comment]
This link isn't working for me either. I can wait if you're working to fix it! Just wanted to make sure it was on your radar.
![Screenshot 2024-05-14 at 11 10 55 AM](https://github.com/ImmuneDynamics/Spectre/assets/35476290/0ffa8657-c7eb-490c-82a0-c4aba9d4be97)

**Comment by tomashhurst** [comment]
Hmm that's very odd -- I can see it OK even if not signed in, maybe I've broken something. If you email me at thomas.ashhurst@sydney.edu.au I can just send you the PDF.
<img width="727" alt="image" src="https://github.com/ImmuneDynamics/Spectre/assets/11766139/7b7747b2-9dfb-40ad-bcff-8abe5a2b1444">

**Comment by tomashhurst** [comment]
@mariecrane updated page for the CytoNorm workflow here: https://immunedynamics.io/spectre/cytonorm/. Give it a try and let us know if it makes sense.
