### ISSUE TITLE
error in Coarse alignment

### ISSUE THREAD

**Issue by MayaCyTOFnewbie** [ImmuneDynamics/Spectre#19]
Hello,

I am running a pilot experiment using the wonderful tutorials you provided. thanks a lot!

I had encountered in error while running 
       crs.dat <- run.align(ref.dat = ref.dat, 
                                target.dat = crs.dat, 
                                batch.col = batch.col, 
                                align.cols = to.align, 
                                method = method, 
                                ...
I would like to point out that I don't really have batches here, I am just trying to test the panel, and the analysis with a small number of samples, before I start a big project.

### This is the output and the error: 
Alignment - setting up
Alignment - preparing reference and target files
Alignment - applying alignment process
[1] 2021-04-12 16:28:24  BatchAdjust.R
[1] basedir:.
[1] outdir:OUTPUT
[1] channelsFile:ChannelsToAdjust.txt
[1] batchKeyword:BATCH_
[1] anchorKeyword:Ref
[1] transformation:FALSE
[1] method:95p
[1] Reading channels file: ChannelsToAdjust.txt
[1] Adjusting 24 channels.
[1] batchesToAdjust:
[1] 1
[1] 2021-04-12 16:28:24  Start loading events batch: 1 (1 of 1)
**Error in png(filename = file.path(postdir, "ScalingFactors.png"), width = pngwidth,  : 
  invalid 'width' or 'height'**

### this is the session info:
> session_info()
- Session info --------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Hebrew_Israel.1255          
 ctype    Hebrew_Israel.1255          
 tz       Asia/Jerusalem              
 date     2021-04-12                  

- Packages ------------------------------------------------------------------------------------------------------------------------------------------------------
 ! package              * version    date       lib source                                 
   abind                  1.4-5      2016-07-21 [1] CRAN (R 4.0.3)                         
   askpass                1.1        2019-01-13 [1] CRAN (R 4.0.3)                         
   assertthat             0.2.1      2019-03-21 [1] CRAN (R 4.0.3)                         
   aws.s3                 0.3.21     2020-04-07 [1] CRAN (R 4.0.3)                         
   aws.signature          0.6.0      2020-06-01 [1] CRAN (R 4.0.3)                         
   backports              1.2.1      2020-12-09 [1] CRAN (R 4.0.3)                         
   base64enc              0.1-3      2015-07-28 [1] CRAN (R 4.0.3)                         
   beachmat               2.6.4      2020-12-20 [1] Bioconductor                           
   beeswarm               0.3.1      2021-03-07 [1] CRAN (R 4.0.4)                         
   BH                   * 1.75.0-0   2021-01-11 [1] CRAN (R 4.0.3)                         
   Biobase              * 2.50.0     2020-10-27 [1] Bioconductor                           
   BiocGenerics         * 0.36.0     2020-10-27 [1] Bioconductor                           
 V BiocManager            1.30.10    2021-03-28 [1] CRAN (R 4.0.5)                         
   BiocNeighbors          1.8.2      2020-12-07 [1] Bioconductor                           
   BiocParallel           1.24.1     2020-11-06 [1] Bioconductor                           
   BiocSingular           1.6.0      2020-10-27 [1] Bioconductor                           
   bitops                 1.0-6      2013-08-17 [1] CRAN (R 4.0.3)                         
 V broom                  0.7.5      2021-04-05 [1] CRAN (R 4.0.3)                         
   cachem                 1.0.4      2021-02-13 [1] CRAN (R 4.0.4)                         
   Cairo                  1.5-12.2   2020-07-07 [1] CRAN (R 4.0.3)                         
 V callr                  3.5.1      2021-03-28 [1] CRAN (R 4.0.4)                         
   car                    3.0-10     2020-09-29 [1] CRAN (R 4.0.3)                         
   carData                3.0-4      2020-05-22 [1] CRAN (R 4.0.3)                         
   CATALYST             * 1.14.0     2020-10-27 [1] Bioconductor                           
   cellranger             1.1.0      2016-07-27 [1] CRAN (R 4.0.3)                         
   circlize               0.4.12     2021-01-08 [1] CRAN (R 4.0.3)                         
 V cli                    2.3.1      2021-04-05 [1] CRAN (R 4.0.3)                         
   clue                   0.3-58     2020-12-03 [1] CRAN (R 4.0.3)                         
   cluster                2.1.0      2019-06-19 [2] CRAN (R 4.0.3)                         
   codetools              0.2-18     2020-11-04 [1] CRAN (R 4.0.3)                         
   colorRamps           * 2.3        2012-10-29 [1] CRAN (R 4.0.3)                         
   colorspace             2.0-0      2020-11-11 [1] CRAN (R 4.0.3)                         
   ComplexHeatmap         2.6.2      2020-11-12 [1] Bioconductor                           
   ConsensusClusterPlus   1.54.0     2020-10-27 [1] Bioconductor                           
   corpcor                1.6.9      2017-04-01 [1] CRAN (R 4.0.3)                         
   cowplot              * 1.1.1      2020-12-30 [1] CRAN (R 4.0.3)                         
   crayon                 1.4.1      2021-02-08 [1] CRAN (R 4.0.3)                         
   curl                   4.3        2019-12-02 [1] CRAN (R 4.0.3)                         
   cytolib                2.2.1      2021-01-17 [1] Bioconductor                           
   CytoML                 2.2.1      2020-11-03 [1] Bioconductor                           
   data.table           * 1.14.0     2021-02-21 [1] CRAN (R 4.0.4)                         
   DBI                    1.1.1      2021-01-15 [1] CRAN (R 4.0.3)                         
   DelayedArray           0.16.1     2021-01-22 [1] Bioconductor                           
   DelayedMatrixStats     1.12.3     2021-02-09 [1] Bioconductor                           
   DEoptimR               1.0-8      2016-11-19 [1] CRAN (R 4.0.3)                         
   desc                   1.3.0      2021-03-05 [1] CRAN (R 4.0.4)                         
   devtools             * 2.3.2      2020-09-18 [1] CRAN (R 4.0.3)                         
   digest                 0.6.27     2020-10-24 [1] CRAN (R 4.0.3)                         
   dplyr                * 1.0.5      2021-03-05 [1] CRAN (R 4.0.4)                         
   drc                    3.0-1      2016-08-30 [1] CRAN (R 4.0.3)                         
   ellipse                0.4.2      2020-05-27 [1] CRAN (R 4.0.3)                         
   ellipsis               0.3.1      2020-05-15 [1] CRAN (R 4.0.3)                         
   fansi                  0.4.2      2021-01-15 [1] CRAN (R 4.0.3)                         
   farver                 2.1.0      2021-02-28 [1] CRAN (R 4.0.4)                         
   fastmap                1.1.0      2021-01-25 [1] CRAN (R 4.0.3)                         
   fda                    5.1.9      2020-12-16 [1] CRAN (R 4.0.3)                         
   fds                    1.8        2018-10-31 [1] CRAN (R 4.0.3)                         
   flowClust              3.28.0     2020-10-27 [1] Bioconductor                           
   flowCore             * 2.2.0      2020-10-27 [1] Bioconductor                           
   FlowSOM              * 1.22.0     2020-10-27 [1] Bioconductor                           
   flowStats              4.2.0      2020-10-27 [1] Bioconductor                           
   flowViz              * 1.54.0     2020-10-27 [1] Bioconductor                           
   flowWorkspace        * 4.2.0      2020-10-27 [1] Bioconductor                           
   forcats                0.5.1      2021-01-27 [1] CRAN (R 4.0.3)                         
   foreign                0.8-81     2020-12-22 [1] CRAN (R 4.0.3)                         
   fs                     1.5.0      2020-07-31 [1] CRAN (R 4.0.3)                         
   generics               0.1.0      2020-10-31 [1] CRAN (R 4.0.3)                         
   GenomeInfoDb         * 1.26.2     2020-12-08 [1] Bioconductor                           
   GenomeInfoDbData       1.2.4      2021-01-19 [1] Bioconductor                           
   GenomicRanges        * 1.42.0     2020-10-27 [1] Bioconductor                           
   GetoptLong             1.0.5      2020-12-15 [1] CRAN (R 4.0.3)                         
   ggbeeswarm             0.6.0      2017-08-07 [1] CRAN (R 4.0.3)                         
   ggcyto               * 1.18.0     2020-10-27 [1] Bioconductor                           
   ggplot2              * 3.3.3      2020-12-30 [1] CRAN (R 4.0.3)                         
   ggpointdensity       * 0.1.0      2019-08-28 [1] CRAN (R 4.0.4)                         
   ggpubr               * 0.4.0      2020-06-27 [1] CRAN (R 4.0.4)                         
   ggrepel                0.9.1      2021-01-15 [1] CRAN (R 4.0.3)                         
   ggridges               0.5.3      2021-01-08 [1] CRAN (R 4.0.3)                         
   ggsignif               0.6.1      2021-02-23 [1] CRAN (R 4.0.4)                         
   ggthemes             * 4.2.4      2021-01-20 [1] CRAN (R 4.0.3)                         
   GlobalOptions          0.1.2      2020-06-10 [1] CRAN (R 4.0.3)                         
   glue                   1.4.2      2020-08-27 [1] CRAN (R 4.0.3)                         
   graph                  1.68.0     2020-10-27 [1] Bioconductor                           
   gridExtra            * 2.3        2017-09-09 [1] CRAN (R 4.0.3)                         
   gtable                 0.3.0      2019-03-25 [1] CRAN (R 4.0.3)                         
   gtools                 3.8.2      2020-03-31 [1] CRAN (R 4.0.3)                         
   haven                  2.3.1      2020-06-01 [1] CRAN (R 4.0.3)                         
   hdrcde                 3.4        2021-01-18 [1] CRAN (R 4.0.3)                         
   hexbin                 1.28.2     2021-01-08 [1] CRAN (R 4.0.3)                         
   hms                    1.0.0      2021-01-13 [1] CRAN (R 4.0.3)                         
   httr                   1.4.2      2020-07-20 [1] CRAN (R 4.0.3)                         
   IDPmisc                1.1.20     2020-01-21 [1] CRAN (R 4.0.3)                         
   igraph               * 1.2.6      2020-10-06 [1] CRAN (R 4.0.3)                         
   IRanges              * 2.24.1     2020-12-12 [1] Bioconductor                           
   irlba                  2.3.3      2019-02-05 [1] CRAN (R 4.0.3)                         
   jpeg                   0.1-8.1    2019-10-24 [1] CRAN (R 4.0.3)                         
   jsonlite               1.7.2      2020-12-09 [1] CRAN (R 4.0.3)                         
   KernSmooth             2.23-18    2020-10-29 [1] CRAN (R 4.0.3)                         
   ks                     1.12.0     2021-02-07 [1] CRAN (R 4.0.3)                         
   labeling               0.4.2      2020-10-20 [1] CRAN (R 4.0.3)                         
   lattice              * 0.20-41    2020-04-02 [2] CRAN (R 4.0.3)                         
   latticeExtra           0.6-29     2019-12-19 [1] CRAN (R 4.0.3)                         
   lifecycle              1.0.0      2021-02-15 [1] CRAN (R 4.0.3)                         
   magrittr               2.0.1      2020-11-17 [1] CRAN (R 4.0.3)                         
   MASS                   7.3-53     2020-09-09 [2] CRAN (R 4.0.3)                         
   Matrix                 1.2-18     2019-11-27 [1] CRAN (R 4.0.3)                         
   MatrixGenerics       * 1.2.1      2021-01-30 [1] Bioconductor                           
   matrixStats          * 0.58.0     2021-01-29 [1] CRAN (R 4.0.3)                         
   mclust                 5.4.7      2020-11-20 [1] CRAN (R 4.0.3)                         
   memoise                2.0.0      2021-01-26 [1] CRAN (R 4.0.3)                         
   mnormt                 2.0.2      2020-09-01 [1] CRAN (R 4.0.3)                         
   multcomp               1.4-16     2021-02-08 [1] CRAN (R 4.0.3)                         
   munsell                0.5.0      2018-06-12 [1] CRAN (R 4.0.3)                         
   mvtnorm                1.1-1      2020-06-09 [1] CRAN (R 4.0.3)                         
   ncdfFlow             * 2.36.0     2020-10-27 [1] Bioconductor                           
   nnls                   1.4        2012-03-19 [1] CRAN (R 4.0.3)                         
   openCyto             * 2.2.0      2020-10-27 [1] Bioconductor                           
   openssl                1.4.3      2020-09-18 [1] CRAN (R 4.0.3)                         
   openxlsx               4.2.3      2020-10-27 [1] CRAN (R 4.0.3)                         
   pcaPP                  1.9-73     2018-01-14 [1] CRAN (R 4.0.3)                         
   pheatmap             * 1.0.12     2019-01-04 [1] CRAN (R 4.0.3)                         
   pillar                 1.5.1      2021-03-05 [1] CRAN (R 4.0.4)                         
   pkgbuild               1.2.0      2020-12-15 [1] CRAN (R 4.0.3)                         
   pkgconfig              2.0.3      2019-09-22 [1] CRAN (R 4.0.3)                         
   pkgload                1.2.0      2021-02-23 [1] CRAN (R 4.0.5)                         
   plotrix                3.8-1      2021-01-21 [1] CRAN (R 4.0.3)                         
   plyr                 * 1.8.6      2020-03-03 [1] CRAN (R 4.0.3)                         
   png                    0.1-7      2013-12-03 [1] CRAN (R 4.0.3)                         
   prettyunits            1.1.1      2020-01-24 [1] CRAN (R 4.0.3)                         
   processx               3.5.0      2021-03-23 [1] CRAN (R 4.0.3)                         
   ps                     1.6.0      2021-02-28 [1] CRAN (R 4.0.4)                         
   purrr                  0.3.4      2020-04-17 [1] CRAN (R 4.0.3)                         
   R.methodsS3            1.8.1      2020-08-26 [1] CRAN (R 4.0.3)                         
   R.oo                   1.24.0     2020-08-26 [1] CRAN (R 4.0.3)                         
   R.utils                2.10.1     2020-08-26 [1] CRAN (R 4.0.3)                         
   R6                     2.5.0      2020-10-28 [1] CRAN (R 4.0.3)                         
   rainbow                3.6        2019-01-29 [1] CRAN (R 4.0.3)                         
   RBGL                   1.66.0     2020-10-27 [1] Bioconductor                           
   RColorBrewer         * 1.1-2      2014-12-07 [1] CRAN (R 4.0.3)                         
   Rcpp                   1.0.6      2021-01-15 [1] CRAN (R 4.0.4)                         
   RcppArmadillo        * 0.10.2.2.0 2021-03-09 [1] CRAN (R 4.0.4)                         
 D RcppParallel           5.0.3      2021-02-24 [1] CRAN (R 4.0.4)                         
   RCurl                  1.98-1.3   2021-03-16 [1] CRAN (R 4.0.4)                         
   readxl                 1.3.1      2019-03-13 [1] CRAN (R 4.0.3)                         
 V remotes                2.2.0      2021-04-01 [1] CRAN (R 4.0.5)                         
   reshape2               1.4.4      2020-04-09 [1] CRAN (R 4.0.3)                         
   reticulate           * 1.18       2020-10-25 [1] CRAN (R 4.0.4)                         
   Rgraphviz              2.34.0     2020-10-27 [1] Bioconductor                           
   rio                    0.5.26     2021-03-01 [1] CRAN (R 4.0.4)                         
   rjson                  0.2.20     2018-06-08 [1] CRAN (R 4.0.3)                         
   rlang                  0.4.10     2020-12-30 [1] CRAN (R 4.0.3)                         
   robustbase             0.93-7     2021-01-04 [1] CRAN (R 4.0.3)                         
   rprojroot              2.0.2      2020-11-15 [1] CRAN (R 4.0.3)                         
   RProtoBufLib           2.2.0      2020-10-27 [1] Bioconductor                           
   rrcov                  1.5-5      2020-08-03 [1] CRAN (R 4.0.3)                         
   RSpectra               0.16-0     2019-12-01 [1] CRAN (R 4.0.3)                         
   rstatix                0.7.0      2021-02-13 [1] CRAN (R 4.0.4)                         
   rstudioapi           * 0.13       2020-11-12 [1] CRAN (R 4.0.3)                         
   rsvd                   1.0.3      2020-02-17 [1] CRAN (R 4.0.3)                         
   Rtsne                * 0.15       2018-11-10 [1] CRAN (R 4.0.3)                         
   S4Vectors            * 0.28.1     2020-12-09 [1] Bioconductor                           
   sandwich               3.0-0      2020-10-02 [1] CRAN (R 4.0.3)                         
   scales               * 1.1.1      2020-05-11 [1] CRAN (R 4.0.3)                         
 V scater                 1.18.3     2021-02-27 [1] Bioconductor                           
   scuttle                1.0.4      2020-12-17 [1] Bioconductor                           
   sessioninfo            1.1.1      2018-11-05 [1] CRAN (R 4.0.3)                         
   shape                  1.4.5      2020-09-13 [1] CRAN (R 4.0.3)                         
   SingleCellExperiment * 1.12.0     2020-10-28 [1] Bioconductor                           
   sparseMatrixStats      1.2.1      2021-02-02 [1] Bioconductor                           
   Spectre              * 0.4.1      2021-03-25 [1] Github (immunedynamics/spectre@ed9f9c0)
   stringi                1.5.3      2020-09-09 [1] CRAN (R 4.0.3)                         
   stringr                1.4.0      2019-02-10 [1] CRAN (R 4.0.3)                         
   SummarizedExperiment * 1.20.0     2020-10-28 [1] Bioconductor                           
   survival               3.2-7      2020-09-28 [2] CRAN (R 4.0.3)                         
   testthat               3.0.2      2021-02-14 [1] CRAN (R 4.0.4)                         
   TH.data                1.0-10     2019-01-21 [1] CRAN (R 4.0.3)                         
   tibble                 3.1.0      2021-02-25 [1] CRAN (R 4.0.4)                         
   tidyr                * 1.1.3      2021-03-03 [1] CRAN (R 4.0.4)                         
   tidyselect             1.1.0      2020-05-11 [1] CRAN (R 4.0.3)                         
   tmvnsim                1.0-2      2016-12-15 [1] CRAN (R 4.0.3)                         
   tsne                   0.1-3      2016-07-15 [1] CRAN (R 4.0.3)                         
   umap                 * 0.2.7.0    2020-11-04 [1] CRAN (R 4.0.4)                         
   usethis              * 2.0.1      2021-02-10 [1] CRAN (R 4.0.3)                         
   utf8                   1.2.1      2021-03-12 [1] CRAN (R 4.0.4)                         
   vctrs                  0.3.6      2020-12-17 [1] CRAN (R 4.0.3)                         
   vipor                  0.4.5      2017-03-22 [1] CRAN (R 4.0.3)                         
   viridis                0.5.1      2018-03-29 [1] CRAN (R 4.0.3)                         
   viridisLite            0.3.0      2018-02-01 [1] CRAN (R 4.0.3)                         
   withr                  2.4.1      2021-01-26 [1] CRAN (R 4.0.3)                         
   XML                    3.99-0.6   2021-03-16 [1] CRAN (R 4.0.4)                         
   xml2                   1.3.2      2020-04-23 [1] CRAN (R 4.0.3)                         
   XVector                0.30.0     2020-10-28 [1] Bioconductor                           
   yaml                   2.2.1      2020-02-01 [1] CRAN (R 4.0.3)                         
   zip                    2.1.1      2020-08-27 [1] CRAN (R 4.0.3)                         
   zlibbioc               1.36.0     2020-10-28 [1] Bioconductor                           
   zoo                    1.8-9      2021-03-09 [1] CRAN (R 4.0.4)                         

[1] C:/Users/MayaB.MEDICINE/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.3/library

 V -- Loaded and on-disk version mismatch.
 D -- DLL MD5 mismatch, broken installation.

thanks!!

Maya

**Comment by tomashhurst** [comment]
Hi Maya,

Hmm that's a bit odd -- seems to be an issue with PNG rendering. Let me have a look into it.

Tom

**Comment by mayanbriller** [comment]
Having the same problem while trying to run on a remote computer.

```
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  : 
  unable to start device PNG
Calls: run.align ... BatchAdjust -> getScalingFactors -> barplot_scalingFactors -> png
In addition: Warning message:
In png(filename = file.path(postdir, "ScalingFactors.png"), width = pngwidth,  :
  unable to open connection to X11 display ''
```

**Comment by tomashhurst** [comment]
Hi @MayaCyTOFnewbie , @mayanbriller , 

These actually look like two separate issues, which is little strange. I'm having a look through the code, so I'll see if I can remove the offending sections. In the meantime, we have a [new batch alignment workflow](https://wiki.centenary.org.au/x/zGCdCw) in a single script (the link to the original workflow you are referencing here is still available, and is listed at the top of this new workflow. The new workflow doesn't do the initial percentile adjustment, so if your batch effects aren't too large, this should work as is. Give it a try and let me know how it goes.

You can find the new workflow [here on the development branch](https://github.com/ImmuneDynamics/Spectre/tree/development/worked_examples/Alignment_workflow). You don't need to update Spectre, it's just the workflow script that isn't in the main release yet.
