### ISSUE TITLE
Errors and questions regarding "Spetre 3- discovery clustering" script

### ISSUE THREAD

**Issue by MayaCyTOFnewbie** [ImmuneDynamics/Spectre#24]
Hi,

I am working on the script "Spetre 3- discovery clustering" and I ran into a few errors

Background: I am now testing a cyTOF panel on three samples: 2 prot1 fixed whole blood and one PBMC sample.

The errors that I encountered: 
>         make.pheatmap(exp, "FlowSOM_metacluster", plot.cols = cellular.cols)
Error in hclust(d, method = method) : 
  NA/NaN/Inf in foreign function call (arg 10)

>         make.pheatmap(annot.exp, "Population", plot.cols = cellular.cols)
Error in hclust(d, method = method) : 
  NA/NaN/Inf in foreign function call (arg 10)

Additionally, I have a few questions regarding the script:
1. Setup preferences section: what is the difference between cellular.cols and clustering.cols?
2. Run clustering and dimensionality reduction section: how does run.flowsom "auto" selection for number of clusters works?
3. Percent positive plots and cutoffs section: what is the perc.pos.markers and perc.pos.cutoffs?
4. Write summary data section: How to convert this section for cyTOF data?

section info is pasted below

Many thanks!!

Maya 

- Session info --------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Hebrew_Israel.1255          
 ctype    Hebrew_Israel.1255          
 tz       Asia/Jerusalem              
 date     2021-04-19                  

- Packages ------------------------------------------------------------------------------------------------------------------------------------------------------
 ! package              * version  date       lib source                                 
   abind                  1.4-5    2016-07-21 [1] CRAN (R 4.0.3)                         
   askpass                1.1      2019-01-13 [1] CRAN (R 4.0.3)                         
   assertthat             0.2.1    2019-03-21 [1] CRAN (R 4.0.3)                         
   aws.s3                 0.3.21   2020-04-07 [1] CRAN (R 4.0.3)                         
   aws.signature          0.6.0    2020-06-01 [1] CRAN (R 4.0.3)                         
   backports              1.2.1    2020-12-09 [1] CRAN (R 4.0.3)                         
   base64enc              0.1-3    2015-07-28 [1] CRAN (R 4.0.3)                         
   Biobase              * 2.50.0   2020-10-27 [1] Bioconductor                           
   BiocGenerics         * 0.36.0   2020-10-27 [1] Bioconductor                           
   broom                  0.7.6    2021-04-05 [1] CRAN (R 4.0.3)                         
   cachem                 1.0.4    2021-02-13 [1] CRAN (R 4.0.4)                         
   callr                  3.6.0    2021-03-28 [1] CRAN (R 4.0.4)                         
   car                    3.0-10   2020-09-29 [1] CRAN (R 4.0.3)                         
   carData                3.0-4    2020-05-22 [1] CRAN (R 4.0.3)                         
   cellranger             1.1.0    2016-07-27 [1] CRAN (R 4.0.3)                         
   cli                    2.4.0    2021-04-05 [1] CRAN (R 4.0.3)                         
   cluster                2.1.0    2019-06-19 [2] CRAN (R 4.0.3)                         
   colorRamps           * 2.3      2012-10-29 [1] CRAN (R 4.0.3)                         
   colorspace             2.0-0    2020-11-11 [1] CRAN (R 4.0.3)                         
   ConsensusClusterPlus   1.54.0   2020-10-27 [1] Bioconductor                           
   crayon                 1.4.1    2021-02-08 [1] CRAN (R 4.0.3)                         
   curl                   4.3      2019-12-02 [1] CRAN (R 4.0.3)                         
   cytolib                2.2.1    2021-01-17 [1] Bioconductor                           
   CytoML                 2.2.1    2020-11-03 [1] Bioconductor                           
   data.table           * 1.14.0   2021-02-21 [1] CRAN (R 4.0.4)                         
   DBI                    1.1.1    2021-01-15 [1] CRAN (R 4.0.3)                         
   desc                   1.3.0    2021-03-05 [1] CRAN (R 4.0.4)                         
   devtools             * 2.3.2    2020-09-18 [1] CRAN (R 4.0.3)                         
   digest                 0.6.27   2020-10-24 [1] CRAN (R 4.0.3)                         
   dplyr                * 1.0.5    2021-03-05 [1] CRAN (R 4.0.4)                         
   ellipsis               0.3.1    2020-05-15 [1] CRAN (R 4.0.3)                         
   fansi                  0.4.2    2021-01-15 [1] CRAN (R 4.0.3)                         
   farver                 2.1.0    2021-02-28 [1] CRAN (R 4.0.4)                         
   fastmap                1.1.0    2021-01-25 [1] CRAN (R 4.0.3)                         
   flowCore             * 2.2.0    2020-10-27 [1] Bioconductor                           
   FlowSOM              * 1.22.0   2020-10-27 [1] Bioconductor                           
   flowViz              * 1.54.0   2020-10-27 [1] Bioconductor                           
   flowWorkspace          4.2.0    2020-10-27 [1] Bioconductor                           
   forcats                0.5.1    2021-01-27 [1] CRAN (R 4.0.3)                         
   foreign                0.8-81   2020-12-22 [1] CRAN (R 4.0.3)                         
   fs                     1.5.0    2020-07-31 [1] CRAN (R 4.0.3)                         
   generics               0.1.0    2020-10-31 [1] CRAN (R 4.0.3)                         
   ggcyto                 1.18.0   2020-10-27 [1] Bioconductor                           
   ggplot2              * 3.3.3    2020-12-30 [1] CRAN (R 4.0.3)                         
   ggpointdensity       * 0.1.0    2019-08-28 [1] CRAN (R 4.0.4)                         
   ggpubr               * 0.4.0    2020-06-27 [1] CRAN (R 4.0.4)                         
   ggsignif               0.6.1    2021-02-23 [1] CRAN (R 4.0.4)                         
   ggthemes             * 4.2.4    2021-01-20 [1] CRAN (R 4.0.3)                         
   glue                   1.4.2    2020-08-27 [1] CRAN (R 4.0.3)                         
   graph                  1.68.0   2020-10-27 [1] Bioconductor                           
   gridExtra            * 2.3      2017-09-09 [1] CRAN (R 4.0.3)                         
   gtable                 0.3.0    2019-03-25 [1] CRAN (R 4.0.3)                         
   haven                  2.3.1    2020-06-01 [1] CRAN (R 4.0.3)                         
   hexbin                 1.28.2   2021-01-08 [1] CRAN (R 4.0.3)                         
   hms                    1.0.0    2021-01-13 [1] CRAN (R 4.0.3)                         
   httr                   1.4.2    2020-07-20 [1] CRAN (R 4.0.3)                         
   IDPmisc                1.1.20   2020-01-21 [1] CRAN (R 4.0.3)                         
   igraph               * 1.2.6    2020-10-06 [1] CRAN (R 4.0.3)                         
   jpeg                   0.1-8.1  2019-10-24 [1] CRAN (R 4.0.3)                         
   jsonlite               1.7.2    2020-12-09 [1] CRAN (R 4.0.3)                         
   KernSmooth             2.23-18  2020-10-29 [1] CRAN (R 4.0.3)                         
   labeling               0.4.2    2020-10-20 [1] CRAN (R 4.0.3)                         
   lattice              * 0.20-41  2020-04-02 [2] CRAN (R 4.0.3)                         
   latticeExtra           0.6-29   2019-12-19 [1] CRAN (R 4.0.3)                         
   lifecycle              1.0.0    2021-02-15 [1] CRAN (R 4.0.3)                         
   magrittr               2.0.1    2020-11-17 [1] CRAN (R 4.0.3)                         
   MASS                   7.3-53   2020-09-09 [2] CRAN (R 4.0.3)                         
   Matrix                 1.2-18   2019-11-27 [1] CRAN (R 4.0.3)                         
   matrixStats            0.58.0   2021-01-29 [1] CRAN (R 4.0.3)                         
   memoise                2.0.0    2021-01-26 [1] CRAN (R 4.0.3)                         
   munsell                0.5.0    2018-06-12 [1] CRAN (R 4.0.3)                         
   ncdfFlow               2.36.0   2020-10-27 [1] Bioconductor                           
   openssl                1.4.3    2020-09-18 [1] CRAN (R 4.0.3)                         
   openxlsx               4.2.3    2020-10-27 [1] CRAN (R 4.0.3)                         
   pheatmap             * 1.0.12   2019-01-04 [1] CRAN (R 4.0.3)                         
   pillar                 1.5.1    2021-03-05 [1] CRAN (R 4.0.4)                         
   pkgbuild               1.2.0    2020-12-15 [1] CRAN (R 4.0.3)                         
   pkgconfig              2.0.3    2019-09-22 [1] CRAN (R 4.0.3)                         
   pkgload                1.2.0    2021-02-23 [1] CRAN (R 4.0.5)                         
   plyr                 * 1.8.6    2020-03-03 [1] CRAN (R 4.0.3)                         
   png                    0.1-7    2013-12-03 [1] CRAN (R 4.0.3)                         
   prettyunits            1.1.1    2020-01-24 [1] CRAN (R 4.0.3)                         
   processx               3.5.0    2021-03-23 [1] CRAN (R 4.0.3)                         
   ps                     1.6.0    2021-02-28 [1] CRAN (R 4.0.4)                         
   purrr                  0.3.4    2020-04-17 [1] CRAN (R 4.0.3)                         
   R6                     2.5.0    2020-10-28 [1] CRAN (R 4.0.3)                         
   RBGL                   1.66.0   2020-10-27 [1] Bioconductor                           
   RColorBrewer         * 1.1-2    2014-12-07 [1] CRAN (R 4.0.3)                         
   Rcpp                   1.0.6    2021-01-15 [1] CRAN (R 4.0.4)                         
 D RcppParallel           5.0.3    2021-02-24 [1] CRAN (R 4.0.4)                         
   readxl                 1.3.1    2019-03-13 [1] CRAN (R 4.0.3)                         
   remotes                2.3.0    2021-04-01 [1] CRAN (R 4.0.5)                         
   reticulate           * 1.18     2020-10-25 [1] CRAN (R 4.0.4)                         
   Rgraphviz              2.34.0   2020-10-27 [1] Bioconductor                           
   rio                    0.5.26   2021-03-01 [1] CRAN (R 4.0.4)                         
   rlang                  0.4.10   2020-12-30 [1] CRAN (R 4.0.3)                         
   rprojroot              2.0.2    2020-11-15 [1] CRAN (R 4.0.3)                         
   RProtoBufLib           2.2.0    2020-10-27 [1] Bioconductor                           
   RSpectra               0.16-0   2019-12-01 [1] CRAN (R 4.0.3)                         
   rstatix                0.7.0    2021-02-13 [1] CRAN (R 4.0.4)                         
   rstudioapi           * 0.13     2020-11-12 [1] CRAN (R 4.0.3)                         
   Rtsne                * 0.15     2018-11-10 [1] CRAN (R 4.0.3)                         
   S4Vectors              0.28.1   2020-12-09 [1] Bioconductor                           
   scales               * 1.1.1    2020-05-11 [1] CRAN (R 4.0.3)                         
   sessioninfo            1.1.1    2018-11-05 [1] CRAN (R 4.0.3)                         
   Spectre              * 0.4.1    2021-03-25 [1] Github (immunedynamics/spectre@ed9f9c0)
   stringi                1.5.3    2020-09-09 [1] CRAN (R 4.0.3)                         
   stringr                1.4.0    2019-02-10 [1] CRAN (R 4.0.3)                         
   testthat               3.0.2    2021-02-14 [1] CRAN (R 4.0.4)                         
   tibble                 3.1.0    2021-02-25 [1] CRAN (R 4.0.4)                         
   tidyr                * 1.1.3    2021-03-03 [1] CRAN (R 4.0.4)                         
   tidyselect             1.1.0    2020-05-11 [1] CRAN (R 4.0.3)                         
   tinytex                0.31     2021-03-30 [1] CRAN (R 4.0.5)                         
   tsne                   0.1-3    2016-07-15 [1] CRAN (R 4.0.3)                         
   umap                 * 0.2.7.0  2020-11-04 [1] CRAN (R 4.0.4)                         
   usethis              * 2.0.1    2021-02-10 [1] CRAN (R 4.0.3)                         
   utf8                   1.2.1    2021-03-12 [1] CRAN (R 4.0.4)                         
   vctrs                  0.3.6    2020-12-17 [1] CRAN (R 4.0.3)                         
   withr                  2.4.1    2021-01-26 [1] CRAN (R 4.0.3)                         
   xfun                   0.22     2021-03-11 [1] CRAN (R 4.0.4)                         
   XML                    3.99-0.6 2021-03-16 [1] CRAN (R 4.0.4)                         
   xml2                   1.3.2    2020-04-23 [1] CRAN (R 4.0.3)                         
   yaml                   2.2.1    2020-02-01 [1] CRAN (R 4.0.3)                         
   zip                    2.1.1    2020-08-27 [1] CRAN (R 4.0.3)                         
   zlibbioc               1.36.0   2020-10-28 [1] Bioconductor                           

[1] C:/Users/MayaB.MEDICINE/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.3/library

 D -- DLL MD5 mismatch, broken installation.

**Comment by tomashhurst** [comment]
Hi @MayaCyTOFnewbie ,

The ```NA/NaN/Inf in foreign function call (arg 10)``` error usually comes up if you are selecting columns that don't exist, or have lots of NAs. If you just run ```cellular.cols```, what comes up? Do you get all the other plots?

In answer to your questions:

1. Setup preferences section: what is the difference between cellular.cols and clustering.cols?
-- ```cellular.cols``` are essentially anything 'cellular' that we want to measure, whereas ```clustering.cols``` are used explicitly to generate clusters & UMAP dimensions (e.g. activation markers would be cellular markers, but might not be clustering markers).

2. Run clustering and dimensionality reduction section: how does run.flowsom "auto" selection for number of clusters works?
-- It essentially looks for an 'elbow point' in terms of how well it can separate data in a statistically meaningful way. This is tricky though, because such a decision on the part of FlowSOM is going to be most heavily influence by the larger expression patterns, not expression on subtle sub-populations, so we usually recommend setting the metacluster target, and aim high -- as metacluster can always be merged.

3. Percent positive plots and cutoffs section: what is the perc.pos.markers and perc.pos.cutoffs?
-- You can choose a series of markers (e.g. c('CD4_asinh', 'CD8_asinh')) as well as a series of value cutoffs, where values above that will be considered 'positive' (e.g. c(3, 3.5)). It will add the proportion of cells in each population that are 'positive' for those markers.

4. Write summary data section: How to convert this section for cyTOF data?
-- This should run the same for flow and CyTOF data!

Any other questions, let me know!

Tom

**Comment by tomashhurst** [comment]
Hi @MayaCyTOFnewbie, how did you get on with things?

**Comment by MayaCyTOFnewbie** [comment]
Hi @tomashhurst!

thanks for check up with me! I still didn't get that chance to get back to the analysis with Spectre, I hope to do it soon. I will let you know!

best,

Maya
