### ISSUE TITLE
standard.colors not working for make.pheatmap

### ISSUE THREAD

**Issue by pavitraviswanath** [ImmuneDynamics/Spectre#33]
Hi! The standard.colours function of make.pheatmap does not seem to be working. I tried changing the color palette to viridis. While the code runs, the plot that is being printed is the default "BuPu". I used the following code:

```
make.pheatmap(sum.dat.z, 
              sample.col = sample.col, 
              plot.cols = plot.cols, 
              is.fold = TRUE, 
              plot.title = 'Z-score',
              annot.cols = annot.cols,
              dendrograms = 'column',
              row.sep = t.first,
              standard.colours = "viridis")

```

![Pheatmap by Sample](https://user-images.githubusercontent.com/43428054/118062532-59ca7f80-b354-11eb-8eea-7ec02cd2ce70.png)

**Comment by tomashhurst** [comment]
Hi @pavitraviswanath, thanks for reaching out! Indeed the `is.fold = TRUE` is overwriting the colour preferences. I'll make an update so you can choose the colours for the fold-change arrangement too!

**Comment by tomashhurst** [comment]
@pavitraviswanath I've just pushed an update that should fix this -- [update Spectre](https://wiki.centenary.org.au/x/7-kiCw) and try your code again. There is a new argument called `fold.colours` where you can specify colours for when `is.fold = TRUE`.
