### ISSUE TITLE
make.pheatmap() is changing the working directory

### ISSUE THREAD

**Issue by hrj21** [ImmuneDynamics/Spectre#37]
Hi all, 

I'm really enjoying using Spectre. One issue I run into is that the make.pheatmap() function is changing my working directory. I'm using an RStudio project, and have a sub-directory called "plots". When I run the code below, I'm left with "plots" as my working directory and have to set it back.

```
exp <- do.aggregate(cell_dat, marker_cols, by = "FlowSOM_metacluster")

make.pheatmap(exp, 
              "FlowSOM_metacluster", 
              marker_cols,
              path = "plots",
              file.name = "Expression heatmap.png",
              cutree_rows = 9)
```
Best wishes
Hefin

**Comment by tomashhurst** [comment]
Hi @hrj21 ,

Good catch. I'm just looking at the code now and that shouldn't be a problem -- I'll make some updates during the week and push that through. 

Tom

**Comment by tomashhurst** [comment]
Hi @hrj21 ,

I've just pushed a new release which should fix the issue -- go ahead an [update Spectre](https://wiki.centenary.org.au/x/7-kiCw) and try that code again.

Tom
