### ISSUE TITLE
Getting the expression set from Spectre 

### ISSUE THREAD

**Issue by fi1d18** [ImmuneDynamics/Spectre#60]
Hello

I want to convert CYTOF data to a Seurat object

One way is getting the normalised CYTOF

Your software is the only tool I have ever gotten run on my fcs files

In this tutorial 

https://github.com/praneet1988/Analyze_CyTOF_Using_Seurat

The author creates normalised expression data from CYTOF

<img width="1440" alt="a" src="https://user-images.githubusercontent.com/86356901/123096277-d4dc8680-d426-11eb-98e1-0e33a99f46c3.png">

I guess by Spectre this function gives the normalised expression data

`cell.dat <- do.asinh(cell.dat, to.asinh, cofactor = cofactor)`

Right?

But for my case the dimension of cell.dat is too high

```
> dim(cell.dat)
[1] 263086    109
>
```

Can you please help me to get a matrix of normalised values for each marker for each cell by your software given fcs files? or subsetting cell.dat to get the right part?

Thank you so much for any help

**Comment by tomashhurst** [comment]
Hey @fi1d18 , thanks for reaching out! 

That's a a cool question, and it should be pretty straightforward. We have a tutorial on this I've been meaning to finish and put online, but it's unfortunately fallen lower on the 'to do' list. So:

**1. Normalisation**

'Normalised' CyTOF data has a slightly different meaning vs. what it means in scRNAseq. In scRNAseq, normalisation adjusts the counts based on genomic content of the cell, whereas we don't need to do that in CyTOF. However, we do an ArcSinh transformation, which is similar to a log transformation of the data, which is common in scRNAseq. In this case, this is indeed that data you want to use.

You can follow the demo/workflows online up until the end of the arcsinh transformation step, which culminates with this:

```
cell.dat <- do.asinh(cell.dat, to.asinh, cofactor = cofactor)
```

A co-factor of 15 should be suitable for all channels in CyTOF.

**2. Data adjustment**

The key thing you will need to do here is to transpose the table. In scRNAseq (and therefore in Seurat) each column is a cell, and each row is a feature (marker, gene, etc); whereas in CyTOF it's the other way around (each row is a cell, and each column is a feature). So:

```
> dim(cell.dat)
[1] 263086    109
```

...refers to 263086 cells (rows) with 109 features (columns) -- and these 109 features would include the raw data and the asinh transformed data.

So here we want to extract the asinh values on their own, and transpose the table. Here's an example with the demo dataset:

```
> as.matrix(names(demo.asinh))
      [,1]         
 [1,] "FileName"   
 [2,] "NK11"       
 [3,] "CD3"        
 [4,] "CD45"       
 [5,] "Ly6G"       
 [6,] "CD11b"      
 [7,] "B220"       
 [8,] "CD8a"       
 [9,] "Ly6C"       
[10,] "CD4"        
[11,] "NK11_asinh" 
[12,] "CD3_asinh"  
[13,] "CD45_asinh" 
[14,] "Ly6G_asinh" 
[15,] "CD11b_asinh"
[16,] "B220_asinh" 
[17,] "CD8a_asinh" 
[18,] "Ly6C_asinh" 
[19,] "CD4_asinh"  
```

```
new.dat <- demo.asinh[,names(demo.asinh)[c(11:19)], with = FALSE] # Selecting the asinh transformed columns (11:19)
```

```
> new.dat
         NK11_asinh    CD3_asinh CD45_asinh  Ly6G_asinh CD11b_asinh   B220_asinh  CD8a_asinh Ly6C_asinh
     1:  0.04235923  0.040087962   2.627736 -0.33829345    3.388057 -0.040229048  0.08362002  0.8518665
     2:  0.04294540  0.118734817   1.340828 -0.41743573    2.435282  0.086559169  0.03471493  0.4344615
     3:  0.05920201  0.204803270   3.022631 -1.25101677    3.684212  0.415750122  0.28212257  0.8876036
     4:  0.35729716 -0.000233878   2.029655 -0.74509796    2.948184  0.181423123  0.32770787  0.4269784
     5:  0.42713953  0.040024513   2.914359  0.04049443    2.449108 -0.210143906  0.14867171  0.0873703
    ---                                                                                                
169000:  0.81693878  0.072791800   4.142314 -0.31149515    4.042229 -0.007797121 -0.26856390  3.1817517
169001: -0.01026402  0.064144703   4.504101 -0.51715205    3.817492  0.201053740 -0.83574631  2.1394053
169002: -0.18326344 -0.009445510   3.166628 -0.09778240    3.541046  0.123164374 -0.21819650  2.8849492
169003:  0.24590035  0.228005328   4.168089 -0.63716643    3.651633 -0.616293228 -0.20024703  3.0339681
169004:  0.68430866  0.095325863   4.525922 -0.88462254    3.827279 -0.620947819  0.07227267  2.9683779
          CD4_asinh
     1:  0.66171351
     2:  0.30263135
     3:  0.65846851
     4:  0.24725691
     5:  0.78456678
    ---            
169000:  0.95239703
169001:  0.31090687
169002: -0.43920651
169003:  0.06163746
169004: -0.03184782
```

```
new.dat <- as.matrix(new.dat) # converts data.table to a matrix
```

```
new.dat <- t(new.dat) # transposes (i.e. flips) the matrix
```

```
> dim(new.dat)
[1]      9 169004
```

First 6 rows and columns:
```
> new.dat[c(1:6), c(1:6)]
                   [,1]        [,2]        [,3]         [,4]        [,5]        [,6]
NK11_asinh   0.04235923  0.04294540  0.05920201  0.357297160  0.42713953  0.15101436
CD3_asinh    0.04008796  0.11873482  0.20480327 -0.000233878  0.04002451  0.12420540
CD45_asinh   2.62773648  1.34082848  3.02263089  2.029655115  2.91435945  2.15504037
Ly6G_asinh  -0.33829345 -0.41743573 -1.25101677 -0.745097962  0.04049443 -0.56550357
CD11b_asinh  3.38805723  2.43528153  3.68421150  2.948184316  2.44910766  3.19632392
B220_asinh  -0.04022905  0.08655917  0.41575012  0.181423123 -0.21014391  0.09393878
```

That matrix (now with rows = features, and columns = cells) should be able to initiate a Seurat object.

Give it a shot and let me know how it goes! 

Tom

**Comment by fi1d18** [comment]
Extremely nice of you

I tried on my three fcs files

```
> seurat <- CreateSeuratObject(new.dat)
Error in CreateAssayObject(counts = counts, min.cells = min.cells, min.features = min.features,  : 
  No cell names (colnames) names present in the input matrix
> 

```
I then tried

```
> colnames(new.dat)
NULL
> View(new.dat)
> dim(new.dat)
[1]     34 263086
> colnames(new.dat)=make.names(c(1: 263086, "cell"))
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
> colnames(new.dat) <- paste0("cell", seq_along(new.dat))
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
> 
```

I don't know how to put colnames

**Comment by tomashhurst** [comment]
Hmm try:

colnames(new.dat) <- paste0('Cell_', c(1:263086))

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by fi1d18** [comment]
Thanks a million

Sorry, after running your kindly described steps, is it reasonable to have `283086` cells just for three fcs file or something goes wrong with my samples?

**Comment by tomashhurst** [comment]
I guess that's context dependent. `283086` cells across three samples is a little under `100000` cells per sample -- not unreasonable by any measure, but it really depends on how rare your population of interest is. If the cells you are interested in are 1/10000 cells then 100,000 total cells would only give you 10 cells of interest. If they are 1/1000 then that would be 100 cells.
