### ISSUE TITLE
Cellprofiler cannot open module

### ISSUE THREAD

**Issue by sailseem** [ImmuneDynamics/Spectre#71]
Dear developer,
  It is a great package, but when I downloaded this package, I cannot open the project BasicSegmentation_MAC.cpproj through cellprofiler 4.2. Can you help me with that? Thanks a lot.

Fan

**Comment by tomashhurst** [comment]
Hi @sailseem , hmm that's odd. Did you try opening CellProfiler first and then selecting Open --> *BasicSegmentation_MAC.cpproj*?

**Comment by sailseem** [comment]
yes, tried both, neither of them worked. Is there a compatible problem using the new MAC-version cellprofiler? Can you check that if possible? Thanks

**Comment by tomashhurst** [comment]
@sailseem it will probably need a new template file -- I will construct a new one, but if you need it to work in the meantime you can also download CellProfiler v3.

**Comment by hrj21** [comment]
I had similar issue with the Windows pipeline. It actually told me I needed CellProfiler v4, but I only have access to v3). I just reconstructed the pipeline using your very helpful screenshots: https://wiki.centenary.org.au/display/SPECTRE/Protocol%3A+basic+cell+segmentation+using+nuclear+pixel+expansion

**Comment by tomashhurst** [comment]
@sailseem did you manage to get this sorted? We are hoping to do a new release during the week, and I will go back over those template files if need be. @hrj21 did your custom pipeline work OK?

**Comment by hrj21** [comment]
Yes the pipeline I made in CellProfiler v3 using your screenshots seems to work perfectly well. Here's a link: https://drive.google.com/file/d/1py1kgSJ1rFtZ1wdSA6jZ1Dkp5FneGPlZ/view?usp=sharing

**Comment by tomashhurst** [comment]
Awesome!
