### ISSUE TITLE
C stack to high when using create.sumtable

### ISSUE THREAD

**Issue by tammyyyx** [ImmuneDynamics/Spectre#8]
Hi Thomas,

Thanks for the straightforward package! I'm using it for immunological data and I had an error "Error: C stack usage  15924720 is too close to the limit"  when I was trying to use the create.sumtable function. My R version is:  R version 4.0.4 Patched and I also updated the data.table package in case this  create.sumtable is updated. Is there anyway to fix this? 

My total sample size is 3x100,000. Is this perhaps too large?

Thanks!

Regards,

Tammy

**Comment by tomashhurst** [comment]
Hi @tammyyyx, sorry to hear something has gone wrong! Just to clarify, do you mean to say you have 3x samples of ~100,000 rows (i.e. cells) in your data.table? That shouldn't be too large, so perhaps something has gone a bit weird.

**Comment by tomashhurst** [comment]
Hi @tammyyyx , I see the problem. If you run `create.sumtable` as it appears in the discovery workflow:

```
        sum.dat <- create.sumtable(dat = cell.dat, 
                                   sample.col = sample.col,
                                   pop.col = "Population",
                                   use.cols = dyn.cols, 
                                   annot.cols = c(group.col, batch.col), 
                                   counts = counts)
```

... but you don't have a table of cell counts (`counts`), then the function won't work properly. 

If you don't have cell counts, try running the following (essentially just deleting the counts):

```
        sum.dat <- create.sumtable(dat = cell.dat, 
                                   sample.col = sample.col,
                                   pop.col = "Population",
                                   use.cols = dyn.cols, 
                                   annot.cols = c(group.col, batch.col))
```

**Comment by tammyyyx** [comment]
Thanks Thomas! This solves it.

**Comment by tomashhurst** [comment]
@ghar1821 @Felixillion 
FYI -- I'll add a check to the sumtable function to check whether 'counts' is a data.table or not. Might help catch an issue like this, as may come about when following the worked examples
