### ISSUE TITLE
Why does changing meta.k not produce the expected number of clusters?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ImmuneDynamics/Spectre#88]
Hi there, 

I changed meta.k argument in run.flowsom() from 8 to 10 by re-reuning run.flowsom() and run.umap(); however, when I checked the number of clusters as below, it still produced the same number of clusters (8 clusters) and regardless of how many clusters I specified in meta.k, it would only produce 8. 

Would you mind helping me explain this potential error?

Thank you for your help!

```
cell.dat_10 <- run.flowsom(cell.dat, cluster.cols, meta.k = 10)

cell.Nosub_10 <- run.umap(cell.dat_20, cluster.cols)

table(cell.Nosub_20$FlowSOM_metacluster)
```

<img width="626" alt="Screen Shot 2021-08-28 at 5 42 29 PM" src="https://user-images.githubusercontent.com/62179082/131224828-8a3e2203-b894-4602-a7b9-ef88d7d4d73d.png">

<img width="462" alt="Screen Shot 2021-08-28 at 5 43 00 PM" src="https://user-images.githubusercontent.com/62179082/131224842-26f7748e-83f0-4ff2-b030-c1f23a309f0e.png">

**Comment by ghar1821** [comment]
I was able to reproduce the error, and I think it's because the first flowsom run with meta.k set to 8 appends the "FlowSOM_metacluster" column into cell.dat, and when you rerun flowsom with meta.k set to 10, it simply just append yet another column with "FlowSOM_metacluster" name into the original cell.dat.

When you run the command "table", it won't show you that there are indeed 2 "FlowSOM_metacluster" columns. Try using head instead.

```R
cell.dat <- Spectre::demo.asinh
cluster.cols <- names(cell.dat)[c(11:19)]
cell.dat <- run.flowsom(cell.dat, cluster.cols, meta.k = 8)
cell.dat_10 <- run.flowsom(cell.dat, cluster.cols, meta.k = 10)
table(cell.dat$FlowSOM_metacluster)
table(cell.dat_10$FlowSOM_metacluster)
```

Inspection using table:

```
> table(cell.dat$FlowSOM_metacluster)

    1     2     3     4     5     6     7     8 
 6061 72579 67319   559 13995  4423  3641   427 
> table(cell.dat_10$FlowSOM_metacluster)

    1     2     3     4     5     6     7     8 
 6061 72579 67319   559 13995  4423  3641   427 
```

Inspection using head:
```
> head(cell.dat)
          FileName     NK11        CD3     CD45       Ly6G    CD11b      B220     CD8a      Ly6C     CD4 NK11_asinh
1: CNS_Mock_01.csv  42.3719  40.098700  6885.08  -344.7830 14787.30  -40.2399  83.7175  958.7000 711.072 0.04235923
2: CNS_Mock_01.csv  42.9586 119.014000  1780.29  -429.6650  5665.73   86.6673  34.7219  448.2590 307.272 0.04294540
3: CNS_Mock_01.csv  59.2366 206.238000 10248.30 -1603.8400 19894.30  427.8310 285.8800 1008.8300 707.094 0.05920201
4: CNS_Mock_01.csv 364.9480  -0.233878  3740.04  -815.9800  9509.43  182.4200 333.6050  440.0710 249.784 0.35729716
5: CNS_Mock_01.csv 440.2470  40.035200  9191.38    40.5055  5745.82 -211.6940 149.2200   87.4815 867.570 0.42713953
6: CNS_Mock_01.csv 151.5890 124.525000  4256.17  -596.1300 12200.80   94.0770 109.3110  417.4010 352.982 0.15101436
      CD3_asinh CD45_asinh  Ly6G_asinh CD11b_asinh  B220_asinh CD8a_asinh Ly6C_asinh CD4_asinh FlowSOM_cluster
1:  0.040087962   2.627736 -0.33829345    3.388057 -0.04022905 0.08362002  0.8518665 0.6617135              23
2:  0.118734817   1.340828 -0.41743573    2.435282  0.08655917 0.03471493  0.4344615 0.3026313              55
3:  0.204803270   3.022631 -1.25101677    3.684212  0.41575012 0.28212257  0.8876036 0.6584685              64
4: -0.000233878   2.029655 -0.74509796    2.948184  0.18142312 0.32770787  0.4269784 0.2472569              53
5:  0.040024513   2.914359  0.04049443    2.449108 -0.21014391 0.14867171  0.0873703 0.7845668             110
6:  0.124205401   2.155040 -0.56550357    3.196324  0.09393878 0.10909447  0.4061429 0.3460348              24
   FlowSOM_metacluster
1:                   2
2:                   2
3:                   2
4:                   2
5:                   5
6:                   2

> head(cell.dat_10)
          FileName     NK11        CD3     CD45       Ly6G    CD11b      B220     CD8a      Ly6C     CD4 NK11_asinh
1: CNS_Mock_01.csv  42.3719  40.098700  6885.08  -344.7830 14787.30  -40.2399  83.7175  958.7000 711.072 0.04235923
2: CNS_Mock_01.csv  42.9586 119.014000  1780.29  -429.6650  5665.73   86.6673  34.7219  448.2590 307.272 0.04294540
3: CNS_Mock_01.csv  59.2366 206.238000 10248.30 -1603.8400 19894.30  427.8310 285.8800 1008.8300 707.094 0.05920201
4: CNS_Mock_01.csv 364.9480  -0.233878  3740.04  -815.9800  9509.43  182.4200 333.6050  440.0710 249.784 0.35729716
5: CNS_Mock_01.csv 440.2470  40.035200  9191.38    40.5055  5745.82 -211.6940 149.2200   87.4815 867.570 0.42713953
6: CNS_Mock_01.csv 151.5890 124.525000  4256.17  -596.1300 12200.80   94.0770 109.3110  417.4010 352.982 0.15101436
      CD3_asinh CD45_asinh  Ly6G_asinh CD11b_asinh  B220_asinh CD8a_asinh Ly6C_asinh CD4_asinh FlowSOM_cluster
1:  0.040087962   2.627736 -0.33829345    3.388057 -0.04022905 0.08362002  0.8518665 0.6617135              23
2:  0.118734817   1.340828 -0.41743573    2.435282  0.08655917 0.03471493  0.4344615 0.3026313              55
3:  0.204803270   3.022631 -1.25101677    3.684212  0.41575012 0.28212257  0.8876036 0.6584685              64
4: -0.000233878   2.029655 -0.74509796    2.948184  0.18142312 0.32770787  0.4269784 0.2472569              53
5:  0.040024513   2.914359  0.04049443    2.449108 -0.21014391 0.14867171  0.0873703 0.7845668             110
6:  0.124205401   2.155040 -0.56550357    3.196324  0.09393878 0.10909447  0.4061429 0.3460348              24
   FlowSOM_metacluster FlowSOM_cluster FlowSOM_metacluster
1:                   2              23                   2
2:                   2              55                   2
3:                   2              64                   2
4:                   2              53                   2
5:                   5             110                   5
6:                   2              24                   2
```

As you can see there are 2 sets of "FlowSOM_metacluster",  "FlowSOM_cluster" columns.

My suggestion will be to use different metacluster column name if you want to use flowsom multiple times on the same data.frame variable. Something like this:

```R
cell.dat <- Spectre::demo.asinh
cluster.cols <- names(cell.dat)[c(11:19)]
cell.dat <- run.flowsom(cell.dat, cluster.cols, meta.k = 8, meta.clust.name = "FlowSOM_metacluster_8")
cell.dat <- run.flowsom(cell.dat, cluster.cols, meta.k = 10, meta.clust.name = "FlowSOM_metacluster_10")
table(cell.dat$FlowSOM_metacluster_8)
table(cell.dat$FlowSOM_metacluster_10)
```

```
> table(cell.dat$FlowSOM_metacluster_8)

    1     2     3     4     5     6     7     8 
 6061 72579 67319   559 13995  4423  3641   427 
> table(cell.dat$FlowSOM_metacluster_10)

    1     2     3     4     5     6     7     8     9    10 
 6061 72579 66848   559 13307   688  4423   471  3641   427 
```

**Comment by ghar1821** [comment]
Also @tomashhurst, I think we should set the function such that if the meta.clust.name is the same for multiple runs, it will just overwrite the column rather than appending a new one with the same name as one of them will not be accessible. I tried to access the 10 metacluster's result and i couldn't.

**Comment by tomashhurst** [comment]
@ghar1821 @denvercal1234GitHub spot on Givanna, re-running FlowSOM creates a duplicate column with the same name. This make selecting the column by name problematic, as it will just select the first of those columns with matching names. I have been thinking about the best way to change this in the next release. One option as you say @ghar1821 is to over-write the previous column, but another option is to append an integer to the name automatically (e.g. the second time running FlowSOM will create a column called `FlowSOM_metacluster_1`). 

@ghar1821 @denvercal1234GitHub what do you think would be better out of those two options?

**Comment by denvercal1234GitHub** [comment]
I would really love to have the appending of the number of clusters to these 2 columns every time one reruns. (Not to compare between packages as this package is great too, but just thinking about how Seurat also do this for their clustering of RNA). Thank you so much, Tom!

**Comment by ghar1821** [comment]
@tomashhurst Maybe something like appending the meta.k count to the column name will be good, and if the same meta.k is run again, then append the _1, _2, etc. Btw, we should do the same for the FlowSOM_cluster column as well.

@denvercal1234GitHub you can try setting the meta.k to 'auto' and set a very high max.meta number (something like 40). This will instruct FlowSOM to automatically find what it thinks the best meta.k. Thereafter, you can either add or subtract from that number to experiment.
